# Generated by Django 4.2.3 on 2023-07-24 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(default='')),
                ('genero', models.CharField(choices=[('Accion', 'ACCION'), ('Aventura', 'AVENTURA')], max_length=20)),
                ('director', models.CharField(default='', max_length=200)),
                ('año_estreno', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('duracion', models.CharField(max_length=200)),
                ('puntuacion', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='peliculas',
        ),
    ]
