# Generated by Django 4.2.3 on 2023-07-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_pelicula_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='descripcion',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
