# Generated by Django 4.2.3 on 2023-07-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_pelicula_descripcion_alter_pelicula_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='descripcion',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
